### ISSUE TITLE
this simply does not work

### ISSUE THREAD

**Issue by B1278** [azaelgg/Discordapp-TokenGrabber#19]
for one, win32crypt doesnt install (which is not your issue) but commenting out the one line that used it worked. it also tries to get a token from all of the paths and if you are missing one i.e you dont have chrome or canary it stops working. after commenting those out 
```
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\packages\urllib3\connectionpool.py", line 591, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\packages\urllib3\connection.py", line 339, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\packages\urllib3\connection.py", line 349, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "C:\Python39\lib\ssl.py", line 420, in match_hostname
    raise CertificateError("hostname %r "
ssl.SSLCertVerificationError: ("hostname 'ically.net' doesn't match 'www.picking.net'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 413, in send
    resp = conn.urlopen(
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\packages\urllib3\connectionpool.py", line 624, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: ("hostname 'ically.net' doesn't match 'www.picking.net'",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "B:\Recovery\py\Scripts\git\Discordapp-TokenGrabber\main.py", line 219, in <module>
    Grabber().start()
  File "B:\Recovery\py\Scripts\git\Discordapp-TokenGrabber\main.py", line 191, in start
    self.lockOut()
  File "B:\Recovery\py\Scripts\git\Discordapp-TokenGrabber\main.py", line 37, in lockOut
    newEmail = self.newEmail()
  File "B:\Recovery\py\Scripts\git\Discordapp-TokenGrabber\main.py", line 207, in newEmail
    email = self.session.get("https://ically.net/user.php?user=", data={"data": ""}).text
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Owner\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("hostname 'ically.net' doesn't match 'www.picking.net'",)
>>> 
```

**Comment by azaelgg** [comment]
readme.md
